name: Build image based on Legato and Octave master
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      SSH_PRIVATE_KEY:
        required: true

jobs:
  compile:
     name: Compile Legato and Octave master
     runs-on:
        - self-hosted
     steps:
        - name: Checkout flowthings/brkedgepkg
          uses: actions/checkout@v3
          with:
            repository: flowthings/brkedgepkg
            ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
            token: ${{ secrets.RUNNER_TOKEN }}
            submodules: true

        - name: Checkout legato
          run: |
               cd ..
               curl https://storage.googleapis.com/git-repo-downloads/repo > ./repo
               mkdir -p legato-src && cd legato-src
               ../repo init --depth 1  -u git://gerrit.legato/manifest < /dev/null
               ../repo sync -j 1 --fail-fast # options to increase stability
        - name: Docker build
          run: cd .. && docker build -t local brkedgepkg/tools/scripts/build_latest

        - name : Docker run
          run: |
            docker run -v $GITHUB_WORKSPACE/tools/scripts/build_latest:/home/octave/scripts -v $GITHUB_WORKSPACE/../legato_framework:/home/octave/legato_framework -v $GITHUB_WORKSPACE:/home/octave/brkedgepkg local legato
            docker run -v $GITHUB_WORKSPACE/tools/scripts/build_latest:/home/octave/scripts -v $GITHUB_WORKSPACE/../legato_framework:/home/octave/legato_framework -v $GITHUB_WORKSPACE:/home/octave/brkedgepkg local octave
            ls $GITHUB_WORKSPACE/build
